[package]
name = "udt-init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ckb-sdk = { version = "3.2.0", git = "https://github.com/chenyukang/ckb-sdk-rust.git", branch = "pcn-udt"}
ckb-sdk = { path = "/Users/yukang/code/playground/ckb-sdk-rust" }
ckb-types = "0.116.1"
ckb-jsonrpc-types = "0.116.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.30"
hex = "0.4.3"
